#!/bin/bash

if [[ -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -f "${UCVM_INSTALL_PATH}/model/cca/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/cca/lib ./test_cca
    exit
  fi
fi
env DYLD_LIBRARY_PATH=../src ./test_cca

